"""passenger_2

Revision ID: 10c69f09dff5
Revises: b89801dcd682
Create Date: 2023-06-17 08:39:44.262909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c69f09dff5'
down_revision = 'b89801dcd682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_id', sa.String(length=32), nullable=False))
        batch_op.drop_constraint('rides_passanger_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['passenger_id'], ['id'])
        batch_op.drop_column('passanger_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passanger_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rides_passanger_id_fkey', 'users', ['passanger_id'], ['id'])
        batch_op.drop_column('passenger_id')

    # ### end Alembic commands ###
