"""Initial migraiton

Revision ID: fbaaded8cf0a
Revises: 
Create Date: 2023-06-06 19:01:17.151147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaaded8cf0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rides',
    sa.Column('distance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gas_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passenger_id', sa.String(length=32), nullable=False),
    sa.Column('driver_id', sa.String(length=32), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('manufacturer', sa.String(length=254), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('license_plate', sa.String(length=7), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('rides')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
