"""testing_23_06_07v2

Revision ID: bf689da2a4c8
Revises: 050f0582cc00
Create Date: 2023-06-07 10:57:50.654904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf689da2a4c8'
down_revision = '050f0582cc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('updated_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
