# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
    steps:
      - name: Connect to Redis
        run: |
          sudo apt-get install redis-tools
          redis-cli ping
          
  build:
    needs: [container-job]
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with unicode
      env:
        JWT_SECRET_KEY: ${{ secrets.FLASK_JWT_SECRET }}
      run: |
        python -m unittest discover -v -s tests -p "test_*.py"
